import Head from "next/head";
import { Inter } from "next/font/google";
import { SignInForm } from "@/components/SignInForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen w-full">
        <div className="h-full bg-[#000000] hidden  md:flex w-[40%] items-center justify-center">
          <p className="text-[72px] text-white font-[700] leading-[88px]">
            Board.{" "}
          </p>
        </div>
        <div className="h-full flex flex-1 items-center justify-center bg-[#F5F5F5]">
          <SignInForm />
        </div>
      </main>
      
    </>
  );
}
